# -*- coding: utf-8 -*-
"""Lepton Software.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sFCxDbEHZUKYxOYTEXgHZJ5Lrr8oucaZ
"""

import requests
from bs4 import BeautifulSoup

#get the dynamic url from the inspect window on the site
url = 'https://www.bata.in/on/demandware.store/Sites-bata-in-Site/en_IN/Stores-FindStores?lat=21.0&long=78.0&radius=2100.0&userPositionLat=22.3179266&userPositionLong=87.3063601'
#send request to access the url
response = requests.get(url)
response

# we have json link, so convert the file to json
data_json = response.json()

#import required libraries 
import json
import ast
import pandas as pd

#save the json data to a dataframe 
df = pd.DataFrame(data_json['stores'])
df.head()

#save the data to a csv file 
df.to_csv('bata_stores_data.csv')

import os

print(os.getcwd())

